### ISSUE TITLE
cael

### ISSUE THREAD

**Issue by The-Levi** [RogueModeCode/WhatBeatsRock-Cael#1]
why is he here??

**Comment by LoganCasey** [comment]
thats a good question

**Comment by The-Levi** [comment]
screenshot included
![Screenshot (934)](https://github.com/user-attachments/assets/28662aa7-6a9e-42f5-a28f-2d72194c65ab)

**Comment by CaelMarkum** [comment]
Brother was that from one of ur hunger game sims?
